#pragma once

#define COMMANDS_LIST_BASE \
  COMMAND(GET_MODULE_VERSION,          0x0001) \
  COMMAND(NCP_RESET,                   0x0002) \
  COMMAND(GET_ZIGBEE_ROLE,             0x0004) \
  COMMAND(SET_ZIGBEE_ROLE,             0x0005) \
  COMMAND(GET_ZIGBEE_CHANNEL_MASK,     0x0006) \
  COMMAND(SET_ZIGBEE_CHANNEL_MASK,     0x0007) \
  COMMAND(GET_ZIGBEE_CHANNEL,          0x0008) \
  COMMAND(GET_PAN_ID,                  0x0009) \
  COMMAND(SET_PAN_ID,                  0x000a) \
  COMMAND(GET_LOCAL_IEEE_ADDR,         0x000b) \
  COMMAND(SET_LOCAL_IEEE_ADDR,         0x000c) \
  COMMAND(GET_TX_POWER,                0x0010) \
  COMMAND(SET_TX_POWER,                0x0011) \
  COMMAND(GET_RX_ON_WHEN_IDLE,         0x0012) \
  COMMAND(SET_RX_ON_WHEN_IDLE,         0x0013) \
  COMMAND(GET_JOINED,                  0x0014) \
  COMMAND(GET_AUTHENTICATED,           0x0015) \
  COMMAND(SET_NWK_KEY,                 0x001b) \
  COMMAND(GET_EXTENDED_PAN_ID,         0x0023) \
  COMMAND(GET_COORDINATOR_VERSION,     0x0024) \
  COMMAND(SET_TC_POLICY,               0x0032) \
  COMMAND(SET_EXTENDED_PAN_ID,         0x0033) \
  COMMAND(SET_MAX_CHILDREN,            0x0034) \
  COMMAND(AF_SET_SIMPLE_DESC,          0x0101) \
  COMMAND(ZDO_NWK_ADDR_REQ,            0x0201) \
  COMMAND(ZDO_IEEE_ADDR_REQ,           0x0202) \
  COMMAND(ZDO_POWER_DESC_REQ,          0x0203) \
  COMMAND(ZDO_NODE_DESC_REQ,           0x0204) \
  COMMAND(ZDO_SIMPLE_DESC_REQ,         0x0205) \
  COMMAND(ZDO_ACTIVE_EP_REQ,           0x0206) \
  COMMAND(ZDO_MATCH_DESC_REQ,          0x0207) \
  COMMAND(ZDO_BIND_REQ,                0x0208) \
  COMMAND(ZDO_UNBIND_REQ,              0x0209) \
  COMMAND(ZDO_MGMT_LEAVE_REQ,          0x020a) \
  COMMAND(ZDO_PERMIT_JOINING_REQ,      0x020b) \
  COMMAND(ZDO_MGMT_BIND_REQ,           0x020f) \
  COMMAND(ZDO_MGMT_LQI_REQ,            0x0210) \
  COMMAND(ZDO_MGMT_NWK_UPDATE_REQ,     0x0211) \
  COMMAND(APSDE_DATA_REQ,              0x0301) \
  COMMAND(NWK_FORMATION,               0x0401) \
  COMMAND(NWK_DISCOVERY,               0x0402) \
  COMMAND(NWK_GET_IEEE_BY_SHORT,       0x0405) \
  COMMAND(NWK_GET_SHORT_BY_IEEE,       0x0406) \
  COMMAND(NWK_GET_NEIGHBOR_BY_IEEE,    0x0407) \
  COMMAND(NWK_START_WITHOUT_FORMATION, 0x041d)

#define COMMANDS_LIST_IND \
  COMMAND(ZDO_DEV_ANNCE_IND,           0x020c) \
  COMMAND(ZDO_DEV_AUTHORIZED_IND,      0x0214) \
  COMMAND(ZDO_DEV_UPDATE_IND,          0x0215) \
  COMMAND(APSDE_DATA_IND,              0x0306) \
  COMMAND(NWK_REJOINED_IND,            0x0409) \
  COMMAND(NWK_REJOIN_FAILED_IND,       0x040a) \
  COMMAND(NWK_LEAVE_IND,               0x040b)

#define COMMANDS_LIST \
  COMMANDS_LIST_BASE \
  COMMANDS_LIST_IND
